#!/bin/bash

# cronjob:  
# * * * * * /root/loginscan


FILE=/root/.loginold
MAILTO="xyz@xyz.com"

getlogin() {
   last -i -n 1 | awk '$1 !~/wtmp/ && $1 > 0 && $3 !~/95.223.210.72/{printf "%s %s %s %s %s\n" ,$5,$6,$7,$1,$3}'
}
OLD=`head -n 5 $FILE`
NEW="$(getlogin)"
if test "$OLD" != "$NEW"; then
    echo -e "$NEW" > /root/.loginold
    if test "" != "$NEW"; then
       mail -r warnung@kscampus.de -s"Achtung: $HOSTNAME Last-Login-Status geaendert" $MAILTO <<- EOF-EOF
$NEW
EOF-EOF
fi
fi
